// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { useRequest, request } from "./request";

export type { RequestOptions, BaseOptions } from "./request";
