// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'name': string;
  'password-progress': string;
  'progree': string;
  'strength': string;
}
export const cssExports: CssExports;
export default cssExports;
