// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'wx-content': string;
  'wx-qr': string;
}
export const cssExports: CssExports;
export default cssExports;
